name: cryptoTracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get: ^3.10.2
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2
  flutter_expanded_tile: ^0.2.1

dev_dependencies:
  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Coin Tracker"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
